dp6/urls.py
from django.contrib import admin
from django.urls import path,include
import dp6app
from dp6app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample/',views.sample,name="sample"),
    path('myapp/',include("dp6app.urls")),
]

dp6app/urls.py
from django.urls import path
from dp6app import views
app_name="dp6app"
urlpatterns=[
    path('',views.index,name="index"),
    path('home',views.home,name="home"),
    path('fact/<n>',views.fact,name="fact"),
    path('child/',views.child,name="child"),
]

dp6app/models.py
from django.db import models

# Create your models here.

dp6app/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.shortcuts import HttpResponse
from math import factorial

def index(request):
    return HttpResponse("<h1>welcome to views of dp6app</h1>")

def home(request):
    return render(request,"dp6app/home.html",{'pname':"i love my India"})

def fact(request,n):
    n=int(n)
    return HttpResponse("<h1>factorial  of  value {} is:{}</h1>".format(n,factorial(n)))

def child(request):
    return render(request,"child.html")

def sample(request):
    return render(request,"dp6app/sample.html")

templates/child.html
{% extends "dp6app/base.html" %}
{% block title %}
    <title>child.html</title>
{% endblock title %}
{% block content %}
    <h1>welcome to child.html</h1>
    <a href="{% url 'dp6app:home' %}">home</a>
    <a href="{% url 'sample' %}">sample</a>
{% endblock %}

templates/dp6app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        <title>base.html</title>
    {% endblock title %}
</head>
<body>
    <h1>navigation bar</h1>
    {% block content %}
        <h1>welcome to base.html</h1>
    {% endblock content %}
</body>
</html>

templates/dp6app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>dp6app welcomes you to main page</h1>
    <h1>{{pname}}</h1>
    {% block content %}
    <h1>welcome to child.html</h1>
    <a href="{% url 'dp6app:child' %}">child</a>
    <a href="{% url 'sample' %}">sample</a>
    {% endblock %}
</body>
</html>

templates/dp6app/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        <title>sample html</title>
    {% endblock title %}
</head>
<body>
    <h1>navigation bar</h1>
    {% block content %}
        <h1>welcome to sample.html</h1>
        <a href="{% url 'dp6app:home' %}">home</a>
        <a href="{% url 'dp6app:child' %}">child</a>
    {% endblock content %}
</body>
</html>